// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.Service.KoreaPrice;

#nullable disable

namespace TestApp.Migrations.BusanUmgungDb
{
    [DbContext(typeof(BusanUmgungDbContext))]
    [Migration("20230515054246_Int")]
    partial class Int
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestApp.Service.KoreaPrice.BusanUmgungInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("aveCost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cmpName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("dan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("danq")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("goodName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("largeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("maxCost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("midName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("minCost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("poj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("saledate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sizeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BusanUmgungInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
