// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.Service.KoreaWarehouseInfo;

#nullable disable

namespace TestApp.Migrations.WarehouseInfoDb
{
    [DbContext(typeof(WarehouseInfoDbContext))]
    partial class WarehouseInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestApp.Service.KoreaWarehouseInfo.WarehouseInfo", b =>
                {
                    b.Property<string>("WARE_NO")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("COMPANY_ADDRESS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("COMPANY_NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("COMPANY_TEL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FROZEN_AREA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FROZEN_WING_COUNT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GENERAL_AREA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GENERAL_WING_COUNT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PRESIDENT_NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RNUM")
                        .HasColumnType("int");

                    b.Property<string>("STORAGE_AREA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("STORAGE_ITEM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WARE_NO");

                    b.ToTable("WarehouseInfoes");
                });
#pragma warning restore 612, 618
        }
    }
}
